# Generated by Django 5.0 on 2023-12-08 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppClub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='nombre',
            field=models.CharField(max_length=40),
        ),
    ]
