# Generated by Django 5.0 on 2023-12-12 11:13

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppClub', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 12, 8, 13, 40, 346667)),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateTimeField(default=datetime.datetime(2023, 12, 12, 8, 13, 40, 346667))),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppClub.noticia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
